# Generated by Django 4.0.1 on 2022-01-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default=None, upload_to=None, verbose_name='Картинки'),
        ),
    ]
