# Generated by Django 4.0.1 on 2022-01-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='static/media', verbose_name='Картинки'),
        ),
    ]
